// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common-fields.proto

package commonfields

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Source1 struct {
	First                string        `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Common               *CommonFields `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Source1) Reset()         { *m = Source1{} }
func (m *Source1) String() string { return proto.CompactTextString(m) }
func (*Source1) ProtoMessage()    {}
func (*Source1) Descriptor() ([]byte, []int) {
	return fileDescriptor_633383383d1527f2, []int{0}
}

func (m *Source1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source1.Unmarshal(m, b)
}
func (m *Source1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source1.Marshal(b, m, deterministic)
}
func (m *Source1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source1.Merge(m, src)
}
func (m *Source1) XXX_Size() int {
	return xxx_messageInfo_Source1.Size(m)
}
func (m *Source1) XXX_DiscardUnknown() {
	xxx_messageInfo_Source1.DiscardUnknown(m)
}

var xxx_messageInfo_Source1 proto.InternalMessageInfo

func (m *Source1) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *Source1) GetCommon() *CommonFields {
	if m != nil {
		return m.Common
	}
	return nil
}

type Source2 struct {
	Second               string        `protobuf:"bytes,1,opt,name=second,proto3" json:"second,omitempty"`
	Common               *CommonFields `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Source2) Reset()         { *m = Source2{} }
func (m *Source2) String() string { return proto.CompactTextString(m) }
func (*Source2) ProtoMessage()    {}
func (*Source2) Descriptor() ([]byte, []int) {
	return fileDescriptor_633383383d1527f2, []int{1}
}

func (m *Source2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source2.Unmarshal(m, b)
}
func (m *Source2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source2.Marshal(b, m, deterministic)
}
func (m *Source2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source2.Merge(m, src)
}
func (m *Source2) XXX_Size() int {
	return xxx_messageInfo_Source2.Size(m)
}
func (m *Source2) XXX_DiscardUnknown() {
	xxx_messageInfo_Source2.DiscardUnknown(m)
}

var xxx_messageInfo_Source2 proto.InternalMessageInfo

func (m *Source2) GetSecond() string {
	if m != nil {
		return m.Second
	}
	return ""
}

func (m *Source2) GetCommon() *CommonFields {
	if m != nil {
		return m.Common
	}
	return nil
}

type CommonFields struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  int64    `protobuf:"varint,2,opt,name=bar,proto3" json:"bar,omitempty"`
	Baz                  bool     `protobuf:"varint,3,opt,name=baz,proto3" json:"baz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonFields) Reset()         { *m = CommonFields{} }
func (m *CommonFields) String() string { return proto.CompactTextString(m) }
func (*CommonFields) ProtoMessage()    {}
func (*CommonFields) Descriptor() ([]byte, []int) {
	return fileDescriptor_633383383d1527f2, []int{2}
}

func (m *CommonFields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonFields.Unmarshal(m, b)
}
func (m *CommonFields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonFields.Marshal(b, m, deterministic)
}
func (m *CommonFields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonFields.Merge(m, src)
}
func (m *CommonFields) XXX_Size() int {
	return xxx_messageInfo_CommonFields.Size(m)
}
func (m *CommonFields) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonFields.DiscardUnknown(m)
}

var xxx_messageInfo_CommonFields proto.InternalMessageInfo

func (m *CommonFields) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *CommonFields) GetBar() int64 {
	if m != nil {
		return m.Bar
	}
	return 0
}

func (m *CommonFields) GetBaz() bool {
	if m != nil {
		return m.Baz
	}
	return false
}

func init() {
	proto.RegisterType((*Source1)(nil), "commonfields.Source1")
	proto.RegisterType((*Source2)(nil), "commonfields.Source2")
	proto.RegisterType((*CommonFields)(nil), "commonfields.CommonFields")
}

func init() { proto.RegisterFile("common-fields.proto", fileDescriptor_633383383d1527f2) }

var fileDescriptor_633383383d1527f2 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x4d, 0xcb, 0x4c, 0xcd, 0x49, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x81, 0x08, 0x42, 0xc4, 0x94, 0x82, 0xb9, 0xd8, 0x83, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0x0d,
	0x85, 0x44, 0xb8, 0x58, 0xd3, 0x32, 0x8b, 0x8a, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x20, 0x1c, 0x21, 0x23, 0x2e, 0x36, 0x88, 0x06, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x29,
	0x3d, 0x64, 0xfd, 0x7a, 0xce, 0x60, 0x8e, 0x1b, 0x98, 0x13, 0x04, 0x55, 0xa9, 0x14, 0x0a, 0x33,
	0xd4, 0x48, 0x48, 0x8c, 0x8b, 0xad, 0x38, 0x35, 0x39, 0x3f, 0x2f, 0x05, 0x6a, 0x2a, 0x94, 0x47,
	0x96, 0xb1, 0x2e, 0x5c, 0x3c, 0xc8, 0xe2, 0x42, 0x02, 0x5c, 0xcc, 0x69, 0xf9, 0xf9, 0x50, 0x83,
	0x41, 0x4c, 0x90, 0x48, 0x52, 0x62, 0x11, 0xd8, 0x48, 0xe6, 0x20, 0x10, 0x13, 0x22, 0x52, 0x25,
	0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x01, 0x12, 0xa9, 0x72, 0xe2, 0x8b, 0x42, 0x09, 0x81, 0x24, 0x36,
	0x70, 0xb0, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x36, 0x7f, 0xb5, 0x2d, 0x01, 0x00,
	0x00,
}
