// Code generated by protoc-gen-go. DO NOT EDIT.
// source: any-wrapper.proto

package anywrapper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Service1 struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service1) Reset()         { *m = Service1{} }
func (m *Service1) String() string { return proto.CompactTextString(m) }
func (*Service1) ProtoMessage()    {}
func (*Service1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0874e9e167ac76d, []int{0}
}

func (m *Service1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service1.Unmarshal(m, b)
}
func (m *Service1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service1.Marshal(b, m, deterministic)
}
func (m *Service1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service1.Merge(m, src)
}
func (m *Service1) XXX_Size() int {
	return xxx_messageInfo_Service1.Size(m)
}
func (m *Service1) XXX_DiscardUnknown() {
	xxx_messageInfo_Service1.DiscardUnknown(m)
}

var xxx_messageInfo_Service1 proto.InternalMessageInfo

func (m *Service1) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

type Service2 struct {
	Second               string   `protobuf:"bytes,1,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service2) Reset()         { *m = Service2{} }
func (m *Service2) String() string { return proto.CompactTextString(m) }
func (*Service2) ProtoMessage()    {}
func (*Service2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0874e9e167ac76d, []int{1}
}

func (m *Service2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service2.Unmarshal(m, b)
}
func (m *Service2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service2.Marshal(b, m, deterministic)
}
func (m *Service2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service2.Merge(m, src)
}
func (m *Service2) XXX_Size() int {
	return xxx_messageInfo_Service2.Size(m)
}
func (m *Service2) XXX_DiscardUnknown() {
	xxx_messageInfo_Service2.DiscardUnknown(m)
}

var xxx_messageInfo_Service2 proto.InternalMessageInfo

func (m *Service2) GetSecond() string {
	if m != nil {
		return m.Second
	}
	return ""
}

type AnyWrapper struct {
	Inside               *anypb.Any `protobuf:"bytes,1,opt,name=inside,proto3" json:"inside,omitempty"`
	Foo                  string     `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  int64      `protobuf:"varint,3,opt,name=bar,proto3" json:"bar,omitempty"`
	Baz                  bool       `protobuf:"varint,4,opt,name=baz,proto3" json:"baz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AnyWrapper) Reset()         { *m = AnyWrapper{} }
func (m *AnyWrapper) String() string { return proto.CompactTextString(m) }
func (*AnyWrapper) ProtoMessage()    {}
func (*AnyWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0874e9e167ac76d, []int{2}
}

func (m *AnyWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnyWrapper.Unmarshal(m, b)
}
func (m *AnyWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnyWrapper.Marshal(b, m, deterministic)
}
func (m *AnyWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyWrapper.Merge(m, src)
}
func (m *AnyWrapper) XXX_Size() int {
	return xxx_messageInfo_AnyWrapper.Size(m)
}
func (m *AnyWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_AnyWrapper proto.InternalMessageInfo

func (m *AnyWrapper) GetInside() *anypb.Any {
	if m != nil {
		return m.Inside
	}
	return nil
}

func (m *AnyWrapper) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *AnyWrapper) GetBar() int64 {
	if m != nil {
		return m.Bar
	}
	return 0
}

func (m *AnyWrapper) GetBaz() bool {
	if m != nil {
		return m.Baz
	}
	return false
}

func init() {
	proto.RegisterType((*Service1)(nil), "anywrapper.Service1")
	proto.RegisterType((*Service2)(nil), "anywrapper.Service2")
	proto.RegisterType((*AnyWrapper)(nil), "anywrapper.AnyWrapper")
}

func init() { proto.RegisterFile("any-wrapper.proto", fileDescriptor_c0874e9e167ac76d) }

var fileDescriptor_c0874e9e167ac76d = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcc, 0xab, 0xd4,
	0x2d, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a,
	0xcc, 0xab, 0x84, 0x8a, 0x48, 0x71, 0x26, 0xe6, 0x55, 0x42, 0x84, 0x95, 0x14, 0xb8, 0x38, 0x82,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x0d, 0x85, 0x44, 0xb8, 0x58, 0xd3, 0x32, 0x8b, 0x8a, 0x4b,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x25, 0xb8, 0x0a, 0x23, 0x21, 0x31,
	0x2e, 0xb6, 0xe2, 0xd4, 0xe4, 0xfc, 0xbc, 0x14, 0xa8, 0x12, 0x28, 0x4f, 0xa9, 0x80, 0x8b, 0xcb,
	0x31, 0xaf, 0x32, 0x1c, 0x62, 0xbc, 0x90, 0x0e, 0x17, 0x5b, 0x66, 0x5e, 0x71, 0x66, 0x4a, 0x2a,
	0x58, 0x15, 0xb7, 0x91, 0x88, 0x5e, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0x2a, 0xc4, 0xca, 0xa4, 0xd2,
	0x34, 0x3d, 0xc7, 0xbc, 0xca, 0x20, 0xa8, 0x1a, 0x21, 0x01, 0x2e, 0xe6, 0xb4, 0xfc, 0x7c, 0x09,
	0x26, 0xb0, 0x81, 0x20, 0x26, 0x48, 0x24, 0x29, 0xb1, 0x48, 0x82, 0x59, 0x81, 0x51, 0x83, 0x39,
	0x08, 0xc4, 0x84, 0x88, 0x54, 0x49, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x80, 0x44, 0xaa, 0x9c, 0x78,
	0xa2, 0x90, 0x3c, 0x94, 0xc4, 0x06, 0x36, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x06,
	0x15, 0x68, 0xf8, 0x00, 0x00, 0x00,
}
