// Code generated by protoc-gen-go. DO NOT EDIT.
// source: one-big.proto

package onebig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nested1 struct {
	First                string   `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nested1) Reset()         { *m = Nested1{} }
func (m *Nested1) String() string { return proto.CompactTextString(m) }
func (*Nested1) ProtoMessage()    {}
func (*Nested1) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae401eddf894d78e, []int{0}
}

func (m *Nested1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nested1.Unmarshal(m, b)
}
func (m *Nested1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nested1.Marshal(b, m, deterministic)
}
func (m *Nested1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nested1.Merge(m, src)
}
func (m *Nested1) XXX_Size() int {
	return xxx_messageInfo_Nested1.Size(m)
}
func (m *Nested1) XXX_DiscardUnknown() {
	xxx_messageInfo_Nested1.DiscardUnknown(m)
}

var xxx_messageInfo_Nested1 proto.InternalMessageInfo

func (m *Nested1) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

type Nested2 struct {
	Second               string   `protobuf:"bytes,1,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nested2) Reset()         { *m = Nested2{} }
func (m *Nested2) String() string { return proto.CompactTextString(m) }
func (*Nested2) ProtoMessage()    {}
func (*Nested2) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae401eddf894d78e, []int{1}
}

func (m *Nested2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nested2.Unmarshal(m, b)
}
func (m *Nested2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nested2.Marshal(b, m, deterministic)
}
func (m *Nested2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nested2.Merge(m, src)
}
func (m *Nested2) XXX_Size() int {
	return xxx_messageInfo_Nested2.Size(m)
}
func (m *Nested2) XXX_DiscardUnknown() {
	xxx_messageInfo_Nested2.DiscardUnknown(m)
}

var xxx_messageInfo_Nested2 proto.InternalMessageInfo

func (m *Nested2) GetSecond() string {
	if m != nil {
		return m.Second
	}
	return ""
}

type TopWrapper struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  int64    `protobuf:"varint,2,opt,name=bar,proto3" json:"bar,omitempty"`
	Baz                  bool     `protobuf:"varint,3,opt,name=baz,proto3" json:"baz,omitempty"`
	Nested1              *Nested1 `protobuf:"bytes,4,opt,name=nested1,proto3" json:"nested1,omitempty"`
	Nested2              *Nested2 `protobuf:"bytes,5,opt,name=nested2,proto3" json:"nested2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopWrapper) Reset()         { *m = TopWrapper{} }
func (m *TopWrapper) String() string { return proto.CompactTextString(m) }
func (*TopWrapper) ProtoMessage()    {}
func (*TopWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae401eddf894d78e, []int{2}
}

func (m *TopWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopWrapper.Unmarshal(m, b)
}
func (m *TopWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopWrapper.Marshal(b, m, deterministic)
}
func (m *TopWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopWrapper.Merge(m, src)
}
func (m *TopWrapper) XXX_Size() int {
	return xxx_messageInfo_TopWrapper.Size(m)
}
func (m *TopWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TopWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TopWrapper proto.InternalMessageInfo

func (m *TopWrapper) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *TopWrapper) GetBar() int64 {
	if m != nil {
		return m.Bar
	}
	return 0
}

func (m *TopWrapper) GetBaz() bool {
	if m != nil {
		return m.Baz
	}
	return false
}

func (m *TopWrapper) GetNested1() *Nested1 {
	if m != nil {
		return m.Nested1
	}
	return nil
}

func (m *TopWrapper) GetNested2() *Nested2 {
	if m != nil {
		return m.Nested2
	}
	return nil
}

func init() {
	proto.RegisterType((*Nested1)(nil), "onebig.Nested1")
	proto.RegisterType((*Nested2)(nil), "onebig.Nested2")
	proto.RegisterType((*TopWrapper)(nil), "onebig.TopWrapper")
}

func init() { proto.RegisterFile("one-big.proto", fileDescriptor_ae401eddf894d78e) }

var fileDescriptor_ae401eddf894d78e = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcf, 0x4b, 0xd5,
	0x4d, 0xca, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xcf, 0x4b, 0x4d, 0xca,
	0x4c, 0x57, 0x92, 0xe7, 0x62, 0xf7, 0x4b, 0x2d, 0x2e, 0x49, 0x4d, 0x31, 0x14, 0x12, 0xe1, 0x62,
	0x4d, 0xcb, 0x2c, 0x2a, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0x14,
	0x61, 0x0a, 0x8c, 0x84, 0xc4, 0xb8, 0xd8, 0x8a, 0x53, 0x93, 0xf3, 0xf3, 0x52, 0xa0, 0x2a, 0xa0,
	0x3c, 0xa5, 0x19, 0x8c, 0x5c, 0x5c, 0x21, 0xf9, 0x05, 0xe1, 0x45, 0x89, 0x05, 0x05, 0xa9, 0x45,
	0x42, 0x02, 0x5c, 0xcc, 0x69, 0xf9, 0xf9, 0x50, 0x35, 0x20, 0x26, 0x48, 0x24, 0x29, 0xb1, 0x48,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x39, 0x08, 0xc4, 0x84, 0x88, 0x54, 0x49, 0x30, 0x2b, 0x30, 0x6a,
	0x70, 0x80, 0x44, 0xaa, 0x84, 0x34, 0xb9, 0xd8, 0xf3, 0x20, 0x0e, 0x91, 0x60, 0x51, 0x60, 0xd4,
	0xe0, 0x36, 0xe2, 0xd7, 0x83, 0x38, 0x51, 0x0f, 0xea, 0xbe, 0x20, 0x98, 0x3c, 0x42, 0xa9, 0x91,
	0x04, 0x2b, 0x36, 0xa5, 0x46, 0x30, 0xa5, 0x46, 0x4e, 0x1c, 0x51, 0x50, 0x8f, 0x26, 0xb1, 0x81,
	0xfd, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x52, 0x6c, 0x4e, 0x08, 0x01, 0x00, 0x00,
}
